### ISSUE TITLE
Can't compile - undeclared functions?

### ISSUE THREAD

**Issue by jack-jjm** [cloudofoz/raylib-media#2]
Hi! Cool looking project.

Right now I can't compile this due to a number of "undeclared function" errors:

```
src/rmedia.c:940:6: error: call to undeclared function 'IsAudioStreamReady'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  940 |         if (IsAudioStreamReady(media->audioStream))
      |             ^
src/rmedia.c:946:5: error: call to undeclared function 'IsTextureReady'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  946 |         if(IsTextureReady(media->videoTexture))
      |            ^
src/rmedia.c:987:7: error: call to undeclared function 'IsAudioStreamReady'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  987 |                         if(IsAudioStreamReady(media.audioStream))
      |                            ^
src/rmedia.c:995:8: error: call to undeclared function 'IsAudioStreamReady'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  995 |                         if (IsAudioStreamReady(media.audioStream)) 
      |                             ^
src/rmedia.c:1007:8: error: call to undeclared function 'IsAudioStreamReady'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1007 |                         if (IsAudioStreamReady(media.audioStream)) 
      |                             ^
src/rmedia.c:1759:6: error: call to undeclared function 'IsAudioStreamReady'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1759 |         if (IsAudioStreamReady(media->audioStream))
      |             ^
```

As far as I can tell the declarations and implementations of these functions don't appear at all in this repository - is there maybe a file missing or something?

**Comment by jack-jjm** [comment]
Ah, I see - those are Raylib 5.0 functions. I'm using the latest raylib commit and it seems all of the `...Ready` functions have been renamed to `...Valid`.

I could make a PR that fixes it if you like, but you might not want it - the rename is a Raylib 5.5 thing I think, so not official yet.

**Comment by cloudofoz** [comment]
Hi @geajack,

Thank you for your kind words about my project! You're correct that raylib's latest changes in the master branch have introduced some renaming, such as replacing `...Ready` with `...Valid`.
You're not the first to encounter this issue, so I’ve provided a patch to ensure compatibility with these changes.

Please give it a try and let me know if it resolves the issue for you!

Best regards,  
C.

**Comment by jack-jjm** [comment]
I didn't checkout your specific patch, but yes, I did the rename myself too and it fixes the issue, thanks!
