### ISSUE TITLE
Small cracks/chips on audio playing

### ISSUE THREAD

**Issue by raysan5** [cloudofoz/raylib-media#5]
I tried to play the raylib showcase video and I can hear some cracks/chips on audio playing.

I tried to `SetAudioStreamBufferSizeDefault(44100*4);` that usually solves the issue but the issue persists.

I tried the same audio file (.mp3) with raylib `raudio_music_stream` example and it works without cracks/chips.

I think the issue could be related to the audio buffer update process, that I see it's managed internally by `UpdateMediaEx()` on module `rmedia.c`.

**Comment by cloudofoz** [comment]
Hi @raysan5 , thanks for trying it out!
Please refer to [this issue](https://github.com/cloudofoz/raylib-media/issues/4) and let me know if it works for you!

**Comment by raysan5** [comment]
@cloudofoz Great! Indeed it solved the issue! Thank you very much! 😄 

Just note that in my case the cracks/chips were not that dramatic like in that issue. They can be heard just a bit every 2-3 seconds.

**Comment by cloudofoz** [comment]
Excellent! It's great to know that it resolved the issue for you, too. Thank you once again for testing the code.
I will need to increase the default buffer sizes and update the documentation to address this issue better.
