### ISSUE TITLE
Support for loading media from memory.

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [cloudofoz/raylib-media#7]
Would be great to support loading media from memory instead of just from disk, for when i.e. we are loading through a virtual file system such as physfs.

**Comment by cloudofoz** [comment]
Hi @SomeGuyDoinWork ,

Thank you for your interest in my project. I agree that loading from a custom stream could be an interesting feature to add!

I have used PhysFS in some projects myself, so I think that allowing users to implement a reading callback could be a feasible option.

I will have to investigate what I/O options the FFmpeg libav libraries provide.

C.

**Comment by cloudofoz** [comment]
I have added the following function:

```c
RLAPI MediaStream LoadMediaFromStream(MediaStreamReader streamReader, int flags);
```

Here, `MediaStreamReader` is defined as:

```c
typedef struct MediaStreamReader
{
    int     (*readFn) (void* userData, uint8_t* buffer, int bufferSize);    // Read function
    int64_t (*seekFn) (void* userData, int64_t offset, int whence);         // Seek function (can be NULL)
    void*     userData;
} MediaStreamReader;
```

I am planning to add a new example to demonstrate loading a movie from a custom stream to test the functionality. If no issues arise during testing, I will proceed to publish the update.

C.

**Comment by cloudofoz** [comment]
Hi @SomeGuyDoinWork,

I’ve added support for loading media from custom streams and included an example demonstrating how to use it to load a movie from memory. Feel free to check it out, and let me know if you encounter any issues or have further feedback.

Best regards,
C.

**Comment by SomeGuyDoinWork** [comment]
thanks
