### ISSUE TITLE
fix timming

### ISSUE THREAD

**Issue by phreda4** [cloudofoz/raylib-media#8]
https://github.com/cloudofoz/raylib-media/blob/462a9c73cf23a84148136634ea635fae7a93cdc3/src/rmedia.c#L1196

fix the timing of each frame for certain videos, by disassembling the multiplication, precision is not lost.
I reeplace to:

```
AVRational* timebase=&ctx->formatContext->streams[streamCtx->streamIdx]->time_base;
const double nextFrameTime = (double)(avPacket->pts-streamCtx->startPts)*timebase->num/timebase->den;
```

**Comment by cloudofoz** [comment]
Hi @phreda4 ,

thank you for pointing out this very interesting issue! I’ve just pushed your fix to use integer multiplication before floating-point division.
Please feel free to close the issue if everything looks good on your end.

Best, 

C.

**Comment by phreda4** [comment]
nice!! I see this

Best!
Pablo
